# Generated by Django 6.0 on 2025-12-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_customer_name_booking_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile_no',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose',
            field=models.CharField(default='purpose', max_length=200),
            preserve_default=False,
        ),
    ]
